### ISSUE TITLE
Will not work on latest Anaconda Python (3.5), because of pygobject

### ISSUE THREAD

**Issue by thvasilo** [rootkiwi/an2linuxserver#11]
Using Anaconda Python 3.5 pygobject is not available (although it is available for 3.4 [here](https://anaconda.org/fallen/pygobject))

Related issues: [here](https://github.com/jupyter/notebook/issues/462) and [here](https://stackoverflow.com/questions/6397755/im-completly-confused-with-pyobject-pygtk-and-gnome-3-as-well).

Not sure if there's much that can be done from your side, just keep an eye out for 3.5 issues with pygobject.

**Comment by rootkiwi** [comment]
Thanks for letting me know!

**Comment by thvasilo** [comment]
Just a note, I solved this by changing the shebang line of the server script to `#!/usr/bin/python3` from `#!/usr/bin/env python3`

This ensures that the script calls the system Py3 and not the Anaconda one.
