### ISSUE TITLE
Need pair every reboot

### ISSUE THREAD

**Issue by CalebCDE** [rootkiwi/an2linuxserver#13]
Hi,

I need to pair the device with the desktop in every reboot, i have the authorized_certs file in /home/.config/an2linux but nothing, in every reboot i need pair again...

Is any option for make that automatic in the way? Or is some kind of error in my config?

Regards!

**Comment by rootkiwi** [comment]
That should not be necessary, that's what the `authorized_certs` file is for.

What happens? Do you get `Failed TLS handshake notif_conn` message after a reboot when trying to recieve a notification? And then you need to pair again for it to work?

**Comment by CalebCDE** [comment]
Hi again, sorry!! Was my fault, the server doesn't start in my desktop pc because a ' in the start of the line... close that, sorry agin.

**Comment by rootkiwi** [comment]
Okey good, no problems
