### ISSUE TITLE
Some applications do not work (Viber, Google Reminders).

### ISSUE THREAD

**Issue by thvasilo** [rootkiwi/an2linuxserver#16]
I haven't tested this thoroughly but in my experience, although Viber and Google Reminders (created through the Google Now app) create notifications on the phone, they are not getting pushed from A2Linux.

Any idea what might be the cause? I have all apps enabled in the AN2Linux settings/whitelist.

EDIT: Not sure if I should report this to the client repo instead.

**Comment by rootkiwi** [comment]
Thank you for reporting, new version published to Play Store!

Google Reminders was flagged as "local only notifications" which I thought I should block but now I've added a setting for that letting user decide instead.

I also tried Viber:
Viber messages is flagged as: group summary
Viber incoming and active calls is flagged as: ongoing event
So make sure you are not blocking those if you want them to be sent

> EDIT: Not sure if I should report this to the client repo instead.

Yeah anywhere is fine by me

**Comment by thvasilo** [comment]
After changing the new settings, Google Reminders and Calendar now work, as does Viber.
Thanks!
