### ISSUE TITLE
Won't execute

### ISSUE THREAD

**Issue by 3ruce** [rootkiwi/an2linuxserver#23]
So I installed the dependencies

`sudo apt-get install python3 libnotify4 gir1.2-notify-0.7 gir1.2-gdkpixbuf-2.0 python3-gi`

And downloaded an2linuxserver.py

`wget https://github.com/rootkiwi/an2linuxserver/raw/master/an2linuxserver.py`

When I ran 

`python an2linuxserver.py`

I got this error message

```
File "an2linuxserver.py", line 161
    print('\n{}'.format(self.user_input_prompt), end='')
                                                    ^
SyntaxError: invalid syntax
```

Do you know what I might be doing wrong?

**Comment by rootkiwi** [comment]
make sure you are using python 3

`python3 an2linuxserver.py`

**Comment by 3ruce** [comment]
Cool, thanks, sorted!

**Comment by 3ruce** [comment]
And now it works :-)

**Comment by rootkiwi** [comment]
Great :)

**Comment by 3ruce** [comment]
btw, congrats on a first app - I'm very impressed!

**Comment by rootkiwi** [comment]
thank you!

**Comment by ammgws** [comment]
Let's close this too @rootkiwi 

(Sorry for the noise)

**Comment by rootkiwi** [comment]
Yes, you dont have to be sorry, thanks for helping out!
