### ISSUE TITLE
"Dependency missing: python-bluez" but this package is already installed

### ISSUE THREAD

**Issue by hista** [rootkiwi/an2linuxserver#25]
Hi,
When I run I get this message:
`Dependency missing: python-bluez
No module named 'bluetooth'`

But this package is already installed:
`apt-cache policy python-bluez
python-bluez:
  Installed: 0.22-1
  Candidate: 0.22-1
  Version table:
 *** 0.22-1 500
        500 http://deb.debian.org/debian sid/main amd64 Packages
        500 http://deb.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
`

How to solve this issue on debian sid?

Thanks for your kind help :)

**Comment by rootkiwi** [comment]
Are you sure you have bluetooth working and installed all needed bluetooth packages?
I'm not sure what packages that's needed with debian but maybe the `bluetooth` package?

I've not read this but it may be useful to you if you have not read it: https://wiki.debian.org/BluetoothUser

**Comment by hista** [comment]
I've installed all the packages mentionned on your readme, and I usually use bluetooth between my computer and smartphone (to send files for example).

But problem solved because of this webpage: https://stackoverflow.com/questions/23985163/python3-error-no-module-named-bluetooth-on-linux-mint

`sudo pip3 install pybluez`

It works now :-)

Just need to add some features such as answering to some notifications (ie sms) and share clipboard, like kdeconnect does ;-)

**Comment by rootkiwi** [comment]
Great :)

> Just need to add some features such as answering to some notifications (ie sms) and share clipboard, like kdeconnect does ;-)

Hehe

**Comment by BruceZhang1993** [comment]
you should install python3-pybluez instead.

**Comment by ammgws** [comment]
Looks like we can close this issue now @rootkiwi

**Comment by rootkiwi** [comment]
Yes :)
