### ISSUE TITLE
Bluetooth connection problem

### ISSUE THREAD

**Issue by BruceZhang1993** [rootkiwi/an2linuxserver#29]
Mobile Device: LineageOS 14.1 Nougat on OnePlus 2
Connection: Bluetooth
Environment: Gnome on ArchLinux
Problem:
python-pybluez installed.
Mobile has paired and connected to archlinux using bluetooth
An2Linux App cannot connect archlinux using bluetooth
Nougat problem or server-side problem not tested

**Comment by rootkiwi** [comment]
Do you have the setting `bluetooth_server` in your config file set to `on`?

**Comment by BruceZhang1993** [comment]
@rootkiwi my bad.. and the readme didn't tell me how to set config file

don't know where it is

**Comment by BruceZhang1993** [comment]
and it works now, thanks

**Comment by rootkiwi** [comment]
okey great, yeah I should probably add something about that in the readme
