### ISSUE TITLE
No notification on computer side

### ISSUE THREAD

**Issue by esp13** [rootkiwi/an2linuxserver#30]
Hi,
I successfully installed the application on the android phone from F-Droid, configured it, lunched the python server script in a terminal, paired the both over WiFi. => OK

When I check the "Display test notification" the notification appear on the phone it show "Testing  WiFi..." about 3 seconds later "Found no enabled bluetooth server" (i didn't configure any bluetooth stuff cause i don't want to use it over bluetooth) and 3 seconds more nothing.
On computer side nothing happens, no more in the terminal.

My computer as the required soft installed, I'm on linux Mint 17.

Did I miss something?
Thank You

**Comment by rootkiwi** [comment]
> Found no enabled bluetooth server

Yes you don't need to worry about that, that is showed if you have bluetooth enabled on your phone.

> On computer side nothing happens, no more in the terminal.

It's not supposed to happen anything more in terminal, though it is supposed to display a notification with your notification daemon.

You could try this small python program to see if a notification is displayed:
```
#!/usr/bin/env python3
from gi.repository import Notify
Notify.init('example')
Notify.Notification.new('title', 'message', '').show()
```

**Comment by esp13** [comment]
Thank you for you answer,
I launched your python script, it works well.

What can be the problem with an2linux?
I launch the server side application inside terminal can it be a problem for the notifications?

**Comment by rootkiwi** [comment]
> I launched your python script, it works well.
What can be the problem with an2linux?

Strange then I dont know what the problem is. Let me know if you found out.

> I launch the server side application inside terminal can it be a problem for the notifications?

No

**Comment by esp13** [comment]
I found the issue, it was my fault:
I have xprivacy installed, i thought it was ok cause the pairing worked, but obviously it wasn't enought.
I Uncheck all restriction and then... tadaaaa! it works.
thank you for your help

**Comment by rootkiwi** [comment]
okey great :)
