### ISSUE TITLE
no notifications displayed

### ISSUE THREAD

**Issue by euri10** [rootkiwi/an2linuxserver#4]
I got this error
`Error TCPHandler/handle
g-io-error-quark: Timeout was reached (24)`

I tried to debug it and cam to the conclusion it's in `self.notif.show()` that the timeout happens, but I couldn't dig further

**Comment by rootkiwi** [comment]
Hmm, do you have all dependencies installed? What distro are you using?

**Comment by euri10** [comment]
all deps mentioned in the readme are installed, I am on debian testing, I use enlightenment.
May I miss some gnome dependencies not mentioned ?
Just asking because a simple example like
```
from gi.repository import Notify
Notify.init('example')
notif = Notify.Notification.new(
  'Title', 
  'Longer message', 
  'dialog-information'
)
notif.show()
```
return the very same message : `GLib.GError: g-io-error-quark: Timeout was reached (24)
`

**Comment by euri10** [comment]
mmm close that, I was in a weird session without dbus apparently, works fine now, great tool
