### ISSUE TITLE
Can't pair with my device

### ISSUE THREAD

**Issue by Areiser** [rootkiwi/an2linuxserver#5]
[2017-01-03 19:01:06] (TCP) Waiting for connections on port 46352
[2017-01-03 19:02:21] (TCP) Failed TLS handshake pair_request: EOF occurred in violation of protocol (_ssl.c:645)
My phone just keeps saying "Connecting..."

I installed from this AUR (build seemed fine to me, and I manually started the python file first): https://aur.archlinux.org/packages/an2linuxserver-git/

Any ideas?

**Comment by rootkiwi** [comment]
No ideas at the moment sorry, I tried the AUR build and worked fine for me. Are you using wifi? Yes you need to manually run the program or use a service that you can attach to if you want to do pairing.

**Comment by Areiser** [comment]
I am on android 4.4 as well. Maybe I'll debug a bit if I find some free time over the weekend, as it seems it's not only my problem. I hope I'll find something :)

**Comment by rootkiwi** [comment]
Should be fixed now, uploaded to Play Store. Was trying to use unsupported ciphers which was affecting android 4.4 users.

Thanks for reporting!

**Comment by Areiser** [comment]
You were faster, it works now. Thanks very much for the fix, this is awesome!

**Comment by rootkiwi** [comment]
> You were faster

:)
> it works now

Great!
