### ISSUE TITLE
Commas in SSIDs

### ISSUE THREAD

**Issue by andoruB** [rootkiwi/an2linuxserver#50]
Is it possible to change the character that's used to separate the SSIDs in the settings? Right now comma is used, but there are some users (including me) that set their SSIDs to include them. Or perhaps to use some escape character or such, so that it would register the comma as part of a name, rather than as an indication that the following characters are part of another SSID.

**Comment by rootkiwi** [comment]
Right, will implement some fix for that

**Comment by rootkiwi** [comment]
Should be fixed now.

For an actual comma in the SSID you can now escape the comma with a backslash ( \ ).
