### ISSUE TITLE
no advertisable device

### ISSUE THREAD

**Issue by vimalaguti** [rootkiwi/an2linuxserver#55]
Hi, 
when I launch the script for the second time, I get :

`
File "/usr/local/lib/python3.7/dist-packages/bluetooth/bluez.py", line 273, in advertise_service
    protocols)
_bluetooth.error: no advertisable device
`

but I'm connected and paired via bluetooth to my phone.

Infos:
ubuntu 19.10
pybluez globally from pip3 - 0.23
I'm on master branch

**Comment by vimalaguti** [comment]
anyway using the python3-bluez package from apt, and the patch applied to bluetoothd.service looks like it works now

**Comment by rootkiwi** [comment]
Great
