### ISSUE TITLE
Not working with a VPN enabled on the Android device

### ISSUE THREAD

**Issue by Peter-JanGootzen** [rootkiwi/an2linuxserver#9]
I use PrivateInternetAccess VPN on my phone and laptop. When the VPN is enabled on my phone the messages do not come through to my laptop.
The type of the VPN is: L2TO/IPSec PSK.

**Comment by rootkiwi** [comment]
Maybe there is an option in your vpn app that blocks LAN?

**Comment by Peter-JanGootzen** [comment]
Yes so apparently with an android VPN(so that is with the default VPN provider inside the settings) it blocks LAN. There is no way to disable this. So I have installed a different VPN provider app which does have a setting to disable the LAN blocking. I now use the PrivateInternetAccess Android app.
My apologies if I made you try to bust a non-existing bug.

**Comment by rootkiwi** [comment]
Okey that is good to know, oh no worries :)
